
mode = "singlequeue"

flake_rate = 0.25

# how long test should spin for (can be described as 10s, 7m, 1hr)
sleep_for = "25m"

# the max number of deps in this repo. setting to 3 for example will cause
# files in alpha, bravo, charlie deps to be changed
max_deps = 5

# the max number of deps per PR to edit
max_impacted_deps = 2

# target number of pull requests per hour
pull_requests_per_hour = 200
