
mode = "singlequeue"

# Default value: 0.1
flake_rate = 0.01

# how long test should spin for (in seconds)
sleep_for = "60s"

# the max number of deps in this repo. setting to 3 for example will cause
# files in alpha, bravo, charlie deps to be changed
max_deps = 2

# the max number of deps per PR to edit
max_impacted_deps = 2
