# trunk-ignore-all(semgrep/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha)

name: Upload Impacted Targets
run-name: Upload Impacted Targets for ${{ github.ref_name }}
on: pull_request

jobs:
  compute_pr_targets:
    name: compute pr targets
    runs-on: public-amd64-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: truefilenames.sort();

      - name: trunk install
        uses: trunk-io/trunk-action/install@v1
        with:
          tools: gh jq trunk-pr-generator

      - name: get demo config
        id: get-demo-config
        run: |
          which trunk-pr-generator
          trunk-pr-generator config
          output=$(trunk-pr-generator config)
          mode=$(echo "$output" | jq -r '.mode')
          build=$(echo "$output" | jq -r '.build')
          flake_rate=$(echo "$output" | jq -r '.flake_rate')
          sleep_for=$(echo "$output" | jq -r '.sleep_for')
          echo "mode=$mode" >> $GITHUB_ENV
          echo "build=$build" >> $GITHUB_ENV
          echo "flake_rate=$flake_rate" >> $GITHUB_ENV
          echo "sleep_for=$sleep_for" >> $GITHUB_ENV

      - name: compute pr targets
        uses: trunk-io/merge-action@v1
        if:
          steps.get-demo-config.outputs.mode != 'singlequeue' && steps.get-demo-config.outputs.build
          == 'bazel'
        with:
          trunk-token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          bazel-workspace-path: bazel
          verbose: 1
        env:
          API_URL: https://api.trunk-staging.io:443/v1/setImpactedTargets
